[project]
name = "pulumi-docu"
version = "0.1.5"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
pulumi-docu = "docu:main_cli"